### ISSUE TITLE
Never use data URI with properties that might be vendor-prefixed

### ISSUE THREAD

**Issue by porada** [monterail/guidelines#146]
``` scss
.foo {
  background:
    asset-data-url("image-that-cant-be-avoided.png") no-repeat,
    linear-gradient(to bottom, #000, #fff);
}
```

It’s common sense, but this has to be remarked. Even though this example doesn’t use any of the CSS3 mixins and multiple backgrounds are widely supported, `linear-gradient` is still the property to be vendor-prefixed. At the time of writing this, Autoprefixer will output the following:

``` css
.foo {
  background: url("data:image/png;base64,…") no-repeat, -webkit-linear-gradient(top, #000, #fff);
  background: url("data:image/png;base64,…") no-repeat, -o-linear-gradient(top, #000, #fff);
  background: url("data:image/png;base64,…") no-repeat, linear-gradient(to bottom, #000, #fff);
}
```

This means that stylesheet’s weight will be increased by 3 times the size of the image. Of course, this isn’t desired nor acceptable.

There’s no exact solution that’s a golden mean to the problem (and this is just one example—in this case using an `asset-url` for tiny images is also wrong). _Rethink stuff._
