### ISSUE TITLE
When designing components use selectors including semantics.

### ISSUE THREAD

**Issue by sheerun** [monterail/guidelines#44]
For example given following element:

``` html
<div class="fld">
  <span>Folder Name</span>
</div>
```

``` css
/* The Folder Module */
.fld > span {
  padding-left: 20px;
  background: url(icon.png);
}
```

We might want to add another span:

``` css
<div class="fld">
    <span>Folder Name</span>
    <span>(32 items)</span>
</div>
```

It will obviously break the layout. That's because we've styled `span` element. 

> A span or div holds none. A heading has some. A class defined on an element has plenty.

The proper HTML in the first case should look like this:

``` html
<div class="fld">
  <span class="fld-name">Folder Name</span>
</div>
```

``` css
/* The Folder Module */
.fld > .fld-name {
  padding-left: 20px;
  background: url(icon.png);
}
```

Source: [smacss book](http://smacss.com/)
